
import Head from 'next/head'
import Footer from './Footer';
import Header from './Header';
import  style from '../styles/Advertise.module.css';
function advertize() {
    return (
        <>

            <Head>
                <title>Food Port</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" />
                <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet" />
            </Head>

            <Header />
                <div className='banner-about'>
                    <div className='banner-text'>
                        <h3 className='banner-text'>Advertise | FOODPORT </h3>
                    </div>
                </div>
  
 {/*Advertising  packages*/} 

                <div className='container'>
                   
                    <h4><b>Get To Know foodport</b></h4>
                    <h6>Order food and grocery online with the foodport app</h6>
                    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro, dignissimos nulla suscipit optio veritatis dolorum quaerat praesentium. Sint minus doloribus beatae deserunt dignissimos, eligendi aut placeat dolorem incidunt recusandae assumenda.</p>
                <div className="row">
                    <div className="col-md-12">
                    <div className="container mt-3"  id={style.main_packages}>
	<div className={style.package}>
		<div className={style.package__item}>
			<div className={style.package__header}>
				<div className={style.package__name}>Free User</div>
			</div>
			<div className={style.package__body}>
				<div className={style.package__price_container}>
					<div className={style.package__price}>$ 0.00</div>
				</div>
				<ul className={style.package_ul}>
				<li>Lorem, ipsum.</li>
					<li>Lorem, ipsum dolor.</li>
					<li>Lorem, ipsum dolor.</li>
				</ul>
			</div>
			<div className={style.package__footer}>
				<button>AVAIL NOW</button>
			</div>
		</div>
	
	</div>
	<div className={style.package}>
		<div className={style.package__item}>
			<div className={style.package__header}>
				<div className={style.package__name}>Free User</div>
			</div>
			<div className={style.package__body}>
				<div className={style.package__price_container}>
					<div className={style.package__price}>    $ 0.00</div>
				</div>
				<ul className={style.package_ul}>
					<li>Lorem, ipsum.</li>
					<li>Lorem, ipsum dolor.</li>
					<li>Lorem, ipsum dolor.</li>
				</ul>
			</div>
			<div className={style.package__footer}>
				<button>AVAIL NOW</button>
			</div>
		</div>
	
	</div>
	<div className={style.package}>
		<div className={style.package__item}>
			<div className={style.package__header}>
				<div className={style.package__name}>Free User</div>
			</div>
			<div className={style.package__body}>
				<div className={style.package__price_container}>
					<div className={style.package__price}>$ 0.00</div>
				</div>
				<ul className={style.package_ul}>
				<li>Lorem, ipsum.</li>
					<li>Lorem, ipsum dolor.</li>
					<li>Lorem, ipsum dolor.</li>
				</ul>
			</div>
			<div className={style.package__footer}>
				<button>AVAIL NOW</button>
			</div>
		</div>
	
	</div>	
</div>
                    </div>
                </div>

                    </div>


            

            
            <Footer />
        </>
    );
}

export default advertize;