/* eslint-disable react-hooks/rules-of-hooks */
import React,{useState} from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { Row, Col, Typography, Tabs, Spin } from 'antd';
import { connect } from 'react-redux';
import Signup_Form from '../components/Signup_Form';
import { useRouter } from 'next/router'
import { useDispatch } from 'react-redux';
import { login } from '.././components/features/UserSlice'
import regis_style from '../styles/register.module.css'
import { createUserWithEmailAndPassword } from 'firebase/auth';
import { addDoc, collection, serverTimestamp, updateDoc, doc } from 'firebase/firestore'; 
import { db, storage } from '../firebase';
import { auth } from '../firebase';
import { Layout } from 'antd';

import Link from 'next/link';
import { loadStripe } from '@stripe/stripe-js';
import axios from 'axios';

const { Text } = Typography;
const { Title } = Typography;
const { Content } = Layout;




function register({ loading, user,loadingModal }) {

    const [email, setEmail] = useState("")
    const [password, setPassword] = useState("")
    const [name, setName] = useState("");
    const [phone, setPhone] = useState("");
    const [bname, setBName] = useState("");
    const [address, setAddress] = useState("")
    const [btype, setBtype] = useState("")
    const [bankac, setBankac] = useState("")
    const [industry, setIndustry] = useState("")
    const [bweb, setBweb] = useState("")
    const [uids, setUids] = useState("")
    const [hasError, Error] = useState("");
    const [select,setSelect]= React.useState();
    const dispatch = useDispatch();
    const stripePromise = loadStripe(process.env.stripe_public_key)
    const router = useRouter()
    const handleCapacity=(e)=>{
        setSelect(e.target.value);
       
    }
      const registers = async() => {

          createUserWithEmailAndPassword(auth,email,password).then((userAuth) => {
              setUids(userAuth.user.uid)
              localStorage.setItem('email', email);
              localStorage.setItem('accid', accId);
               localStorage.setItem('displayName', name);
          }).catch(function(error) {
            var errorMessage = error.message;
            console.log("errorMessage: "+ errorMessage)
          });
        
          const stripe = await stripePromise;
          const RegisterSession =
           await axios.post('/api/connectedaccount',
              {
                
                  email: email,
              
              })
              const accId= RegisterSession.data.id
                console.log("accId: "+ accId)
                const link=RegisterSession.data.link
                console.log("link: "+ link)
            
    if(select==='user'|| accId!=null){
            const docRef = await addDoc(collection(db, 'userid'), {
                email:email,
                password:password,
                name:name,
                phone:phone,
                select:select,
                bname:bname,
              accId:accId,
              object: "bank_account",
            country: "US",
            currency: "usd",
            routing_number: "110000000",
            account_number: "000123456789",
               
              })
            
    
              router.push(select==='user' ? '/' : link)
            }
       
        // router.push(select==='user' ? '/' : '/ResturentOwner')
      
      }

  return(
      <>
        <Head>
            <title>Food Port</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" />
            <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet" />
        </Head>

        <div className='user-account signup'>
      <div className="container h-100">
        <Row className="h-100" align="middle">
          <Col xs={24} md={12} className="pr-md-5">
            <a href='#'>
              <h2 className="mb-4"><strong>Food</strong>Port</h2>
            </a>

            <Title className='text-center mb-4' level={2}>Signup</Title>
            <Signup_Form  />
            
            <p className="dont-account text-center">By signing up you agree to the <a href="#">terms & conditions</a> and <a href="#">privacy policy</a></p>
            <p className="dont-account text-center pb-3">Alread have an account? <a href='#/auth/login'>Login</a></p>
          </Col>
          <Col xs={24} md={12} className="text-center text-md-right">
            <img className="img-fluid" src="https://i.ibb.co/FKfy4Sh/signup.png" alt="logo" />
          </Col>
        </Row>

      
      </div>
    </div>
    <div className='container-fluid footer'>
        <Row>
        <Col xs={24} sm={16} md={12} className='text-center text-md-left'>
                <Text>Copyright 2020.All rights reserved.</Text>
              </Col>
              <Col xs={24} sm={8} md={12}>
                <ul className='social-icon'>
                  <li>
                    <a href='#'>
                      <i className='fa fa-facebook'></i>
                    </a>
                  </li>
                  <li>
                    <a href='#'>
                      <i className='fa fa-twitter'></i>
                    </a>
                  </li>
                  <li>
                    <a href='#'>
                      <i className='fa fa-youtube'></i>
                    </a>
                  </li>
                </ul>
              </Col>

        </Row>
        </div>
      </>
  );
}

export default register;


